### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Koshi-Y** [Koshi-Y/protospace-35423#1]
# URL
https://protospace-35423.herokuapp.com/

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **プロトタイプ編集ページにて、バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないようにしましょう**


- [x] **正しく編集できた場合は、詳細ページへ遷移するようにしましょう**
現状、トップページに遷移します。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Koshi-Y** [comment]
修正しました！！！
よろしくお願いします。

**Comment by snkw-works** [comment]
@Koshi-Y さん、ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
